# Generated by Django 6.0.5 on 2026-05-20 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sertifikat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200, verbose_name="To'liq F.I.O.")),
                ('tur', models.CharField(choices=[('ustoz', "O'qituvchi"), ('xodim', 'Xodim'), ('talaba', 'Talaba')], max_length=20, verbose_name="Bo'lim turi")),
                ('fakultet', models.CharField(choices=[('mat', 'Muhandislik-axborot texnologiyalari'), ('chet', 'Chet tillar'), ('iqt', 'Iqtisodiyot'), ('ped', 'Pedagogika'), ('ijt', 'Ijtimoiy fanlar'), ('tab', 'Tabiiy fanlar')], max_length=20, verbose_name='Fakultet')),
                ('bolim', models.CharField(max_length=200, verbose_name="Kafedra / Bo'lim / Guruh")),
                ('kurs', models.CharField(blank=True, max_length=30, verbose_name='Kurs')),
                ('nomi', models.CharField(max_length=300, verbose_name='Sertifikat nomi')),
                ('tashkilot', models.CharField(blank=True, max_length=200, verbose_name='Bergan tashkilot')),
                ('link', models.URLField(max_length=500, verbose_name='Sertifikat linki')),
                ('berilgan', models.DateField(blank=True, null=True, verbose_name='Berilgan sana')),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('yuklagan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yuklagan')),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikatlar',
                'ordering': ['-yaratilgan'],
            },
        ),
    ]
