# Generated by Django 6.0.5 on 2026-05-21 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sertifikat',
            name='tur',
            field=models.CharField(choices=[('ustoz', "O'qituvchi"), ('xodim', 'Xodim'), ('talaba', 'Talaba')], max_length=20, verbose_name='Tur'),
        ),
        migrations.AlterField(
            model_name='sertifikat',
            name='yuklagan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(choices=[('ustoz', "O'qituvchi"), ('xodim', 'Xodim'), ('talaba', 'Talaba')], max_length=20, verbose_name='Kim uchun yuklaydi')),
                ('fakultet', models.CharField(choices=[('mat', 'Muhandislik-axborot texnologiyalari'), ('chet', 'Chet tillar'), ('iqt', 'Iqtisodiyot'), ('ped', 'Pedagogika'), ('ijt', 'Ijtimoiy fanlar'), ('tab', 'Tabiiy fanlar')], max_length=20, verbose_name='Fakultet')),
                ('bolim', models.CharField(max_length=200, verbose_name="Kafedra / Bo'lim / Guruh")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi profili',
                'verbose_name_plural': 'Foydalanuvchi profillari',
            },
        ),
    ]
