# Generated by Django 6.0.5 on 2026-05-21 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_old'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fakultet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200, unique=True, verbose_name='Fakultet nomi')),
            ],
            options={
                'verbose_name': 'Fakultet',
                'verbose_name_plural': 'Fakultetlar',
                'ordering': ['nomi'],
            },
        ),
        migrations.RemoveField(
            model_name='sertifikat',
            name='bolim',
        ),
        migrations.RemoveField(
            model_name='sertifikat',
            name='fakultet',
        ),
        migrations.RemoveField(
            model_name='sertifikat',
            name='fio',
        ),
        migrations.RemoveField(
            model_name='sertifikat',
            name='kurs',
        ),
        migrations.RemoveField(
            model_name='sertifikat',
            name='tur',
        ),
        migrations.AlterField(
            model_name='sertifikat',
            name='yuklagan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yuklagan_sertlar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200, verbose_name="Bo'lim nomi")),
                ('kerakli_sert', models.PositiveIntegerField(default=2, verbose_name='Kerakli sertifikat soni (xodim)')),
                ('boshlig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boshqaruv_bolim', to=settings.AUTH_USER_MODEL, verbose_name="Bo'lim boshlig'i")),
            ],
            options={
                'verbose_name': "Bo'lim",
                'verbose_name_plural': "Bo'limlar",
                'ordering': ['nomi'],
            },
        ),
        migrations.CreateModel(
            name='Guruh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, verbose_name='Guruh nomi')),
                ('kurs', models.PositiveSmallIntegerField(default=1, verbose_name='Kurs')),
                ('kerakli_sert', models.PositiveIntegerField(default=1, verbose_name='Kerakli sertifikat soni (talaba)')),
                ('fakultet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guruhlar', to='core.fakultet')),
                ('tyutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tyutor_guruhlar', to=settings.AUTH_USER_MODEL, verbose_name='Tyutor')),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': 'Guruhlar',
                'ordering': ['nomi'],
            },
        ),
        migrations.CreateModel(
            name='Kafedra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200, verbose_name='Kafedra nomi')),
                ('kerakli_sert', models.PositiveIntegerField(default=2, verbose_name="Kerakli sertifikat soni (o'qituvchi)")),
                ('fakultet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kafedralar', to='core.fakultet')),
                ('mudiri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mudirlik_kafedra', to=settings.AUTH_USER_MODEL, verbose_name='Kafedra mudiri')),
            ],
            options={
                'verbose_name': 'Kafedra',
                'verbose_name_plural': 'Kafedralar',
                'ordering': ['nomi'],
            },
        ),
        migrations.CreateModel(
            name='Oqituvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200, verbose_name="To'liq F.I.O.")),
                ('lavozim', models.CharField(blank=True, max_length=200, verbose_name='Lavozim')),
                ('kafedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oqituvchilar', to='core.kafedra')),
            ],
            options={
                'verbose_name': "O'qituvchi",
                'verbose_name_plural': "O'qituvchilar",
                'ordering': ['fio'],
            },
        ),
        migrations.AddField(
            model_name='sertifikat',
            name='oqituvchi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sertifikatlar', to='core.oqituvchi'),
        ),
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200, verbose_name="To'liq F.I.O.")),
                ('guruh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talabalar', to='core.guruh')),
            ],
            options={
                'verbose_name': 'Talaba',
                'verbose_name_plural': 'Talabalar',
                'ordering': ['fio'],
            },
        ),
        migrations.AddField(
            model_name='sertifikat',
            name='talaba',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sertifikatlar', to='core.talaba'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('tyutor', 'Tyutor'), ('bolim_boshlig', "Bo'lim boshlig'i"), ('kafedra_mudiri', 'Kafedra mudiri')], default='tyutor', max_length=30, verbose_name='Rol')),
                ('bolim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bolim', verbose_name="Bo'lim (boshlig' uchun)")),
                ('guruh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.guruh', verbose_name='Guruh (tyutor uchun)')),
                ('kafedra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.kafedra', verbose_name='Kafedra (mudiri uchun)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi profili',
                'verbose_name_plural': 'Foydalanuvchi profillari',
            },
        ),
        migrations.CreateModel(
            name='Xodim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200, verbose_name="To'liq F.I.O.")),
                ('lavozim', models.CharField(blank=True, max_length=200, verbose_name='Lavozim')),
                ('bolim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xodimlar', to='core.bolim')),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'ordering': ['fio'],
            },
        ),
        migrations.AddField(
            model_name='sertifikat',
            name='xodim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sertifikatlar', to='core.xodim'),
        ),
    ]
