# Generated by Django 6.0.5 on 2026-05-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fakultet_remove_sertifikat_bolim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='guruh',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='guruhlar',
            field=models.ManyToManyField(blank=True, related_name='tyutorlar', to='core.guruh', verbose_name='Guruhlar (tyutor uchun)'),
        ),
    ]
